In [ ]:
#local - only available to other code in this scope. A function, for example, only has access to the names defined in that function or passed into it via arguments

#Enclosing - only exists for nested functions. Inner nests can have access to the names in outer nests

#Global - available to all your code and can pass through modules, classes, etc.

#Built-in - all names that are created by Python when you run a script 

#Constructurs - get created when you create an instance of a class

#instance will always run the constructor

__init__(__ is "dunder")

SELF is a default

In [5]:
class a_sample_class:

    #default/basic consructor
    def __init__(self, one, two):
        self.var = 2

    #an instance method for printing
    def print_vars(self):
        print(self.var)

#create instance of class
obj = a_sample_class(2,8)

obj.print_vars()


2


In [ ]:
class a_sample_class:
    class_atr = 5

    def __init__(self, one, two):
        #instance attribute
        self.first = one
        self.second = two
        
#object is instance of class
obj = s_sample_class(17,42)

#instance attribute as property of object
print(obj.first)

#class attribute as property of object
print(obj.class_attr)

#insyance attribute as property of class
print(a_sample_class.first)

#class attribute as property of class
print(a_sample_class.class_atr)


In [ ]:
# Instance Attributes and Class Attributes

#2 scopes for attributes

#instance attribute = variable that belongs to a specific instance of instantiation. Defined inside the constructor (init). Can access from the scope of an object (local)

#class attribute = type of variable that belongs to the class itself. Similar to the static atributes in java (not exactly the same). It is both a property of a class AND a property of the object. We can mutate a class attribute to be an instance attribute


In [6]:
# returning the current module namespace
# namespace = mapping between objects and cirrent names. These are defined names,
# and they also include information about the objects each name references
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'class a_sample_class:\n\n    #default/basic consructor\n    def__init__(self):\n        self.var = 0\n\n#an instance method for printing\ndef print_vars(self):\n    print(self.var)\n\n#create instance of class\nobj = a_sample_class()\n\nobj.print_vars()',
  'class a_sample_class:\n\n    #default/basic consructor\n    def __init__(self):\n        self.var = 0\n\n    #an instance method for printing\n    def print_vars(self):\n        print(self.var)\n\n#create instance of class\nobj = a_sample_class()\n\nobj.print_vars()',
  'class a_sample_class:\n\n    #default/basic consructor\n    def __init__(self):\n        self.var = 0\n\n    #an instance method for printing\n    def print_vars(self):\n        print(self.

In [10]:
class Candy:
    #variables that start with a single underscore are reserved for internal purposes
    def __init__(self, _brand, 
                _is_caramel=False, 
                _is_chocolate=False, 
                _is_vegan=False, 
                _has_nuts=False,
                _type='chocolate',
                _calories=200):
        self.brand = _brand
        self.is_caramel = _is_caramel
        self.is_chocolate = _is_chocolate
        self.is_vegan = _is_vegan
        self.has_nuts = _has_nuts
        self.calories = _calories
        self.type = _type

#class method - used to modify the state of the class (for all instances)
@classmethod
def snickers(cls):
    return cls('Mars' ,_is_caramel=True, _has_nuts=True)

#instance method - can access and modify both the class and instance state
#printing is acccessing state
def dispaly(self):
    print('My favorite candy is [self.brand] {self.type})
#static method - used for comparison or validation
#Commonly used im 
    

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3085951545.py, line 25)

In [ ]:
favorite_candy = Candy(_brand='Hersheys',
                       _is_chocolate=True,
                       _type='Reeces'
                      )
favorite_candy.display()

In [ ]:
def the_decoratopr(func):
    print("decorator is running")
    func()
    print("still running")

def oh_hi():
    print("Hello there!")

hello = the_decorator(oh_hi)

def the_decorator(func):
    print("decorator is running)
    func()
    print("still running")

@the_decorator
def oh_hi():
    print("Hello there!")

In [ ]:
#Encapsulation - implementation details are hidden or encapsulated in objects
#inheirtyance - child classes can inherit from parent classes and  modules
#Polymorphism - obejcts and names exists in many forms. So, the same attribute or method can exist in multiple classes anbd mean different things, etc.
#Abstratcion - handling a concept rather than the implementation details

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

# 1. Arrays can have any number if dimensions,inckduing zero (a scalar)
# 2. Arrays are typed: np.uint8, np.float64, np.float64
# 3. Arrays are dense. Each element of the array exists and had the same type
# 4. Arrays are faster than pyhton lists (consume less memory)
# 5. Can only combine arrays of the same shape!

2 (2, 3) float32


In [7]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
print(x.ndim, x.shape, x.dtype)

2 (3, 3) float32


In [8]:
#1
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
b.ndim
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [10]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]], ndmin=6)
c

array([[[[[[1, 2, 3],
           [4, 5, 6]],

          [[1, 2, 3],
           [4, 5, 6]]]]]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [16]:
a = a.T
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.arange(10).reshape(5,2)

In [17]:
np.sqrt(b)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]])